### ISSUE TITLE
Escaping apostrophes

### ISSUE THREAD

**Issue by wduquette** [tobijk/caius#13]
One of things I'm doing is running caius/Markdown against the mdtest tool's Markdown.mdtest; and one of the differences I see is that caius/Markdown escapes apostrophes as "&apos;", which causes a false negative in the test suite.  It's not wrong, certainly, but I'm never run into any problems with unescaped apostrophes, and I was wondering why you bothered.

**Comment by tobijk** [comment]
Honestly, I don't remember. Probably I just took all the default entities for XML and escaped them. Since generated XHTML attributes are always framed by double-quotes, it should be safe to not escape the apostrophes.

**Comment by tobijk** [comment]
This has been "fixed".
