### ISSUE TITLE
Markdown: _references isn't cleared

### ISSUE THREAD

**Issue by wduquette** [tobijk/caius#14]
Line 52 of Markdown::convert calls "array set" to initialize the _references variable; but "array set" does a merge rather than an assignment.  You need to call  "array unset ::Markdown::_references" just prior to eliminate old references:

```
        array unset ::Markdown::_references
        array set ::Markdown::_references [collect_references markdown]
```

**Comment by tobijk** [comment]
Great catch! Thanks a lot. Fixed in d8a0b10a.
