### ISSUE TITLE
WebDriver is unable to element by_partial_link_text with extend ASCII characters

### ISSUE THREAD

**Issue by mike-white-extr** [tobijk/caius#18]
I have a web interface that has extended ASCII characters  in this case  I am using the 
element by_partial_link_text
with the following text  FranÃ§ais
The page has the following html
<a class="ng-binding">FranÃ§ais</a>
the script can find it if i remove all the extended ascii characters "Fran"
but in the future I will need to find the extended ASCII
If you would like to test it is online at:
https://www.ezcloudx.com/#/
it is from the internationalization pulldown top left.

**Comment by tobijk** [comment]
I won't be able to check this before Monday. In the mean time, please double check that your pages (and your server) advertise the correct page encoding. If I access the page above in iOS I see Francais all garbled which to me seems that it cannot detect the encoding of the page.

**Comment by tobijk** [comment]
As I suspected, the content encoding is not advertised. Please add <meta charset="utf-8" /> to your pages and/or let your server advertise the content encoding. Then your problem will go away.

**Comment by tobijk** [comment]
Closing as invalid.
